//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjunaExample.SubscriptionDemo.RestClient
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using AjunaExample.SubscriptionDemo.RestClient.Generated.Interfaces;
   using AjunaExample.SubscriptionDemo.RestClient.Generated.Clients;
   
   public sealed class Client
   {
      private HttpClient _httpClient;
      private BaseSubscriptionClient _subscriptionClient;
      public IAssetsControllerClient AssetsControllerClient;
      public IAuraControllerClient AuraControllerClient;
      public IBalancesControllerClient BalancesControllerClient;
      public ICouncilControllerClient CouncilControllerClient;
      public ICouncilMembershipControllerClient CouncilMembershipControllerClient;
      public IDemocracyControllerClient DemocracyControllerClient;
      public IGameRegistryControllerClient GameRegistryControllerClient;
      public IGrandpaControllerClient GrandpaControllerClient;
      public IMatchmakerControllerClient MatchmakerControllerClient;
      public IObserversControllerClient ObserversControllerClient;
      public IRunnerControllerClient RunnerControllerClient;
      public ISchedulerControllerClient SchedulerControllerClient;
      public ISidechainControllerClient SidechainControllerClient;
      public ISudoControllerClient SudoControllerClient;
      public ISystemControllerClient SystemControllerClient;
      public ITeerexControllerClient TeerexControllerClient;
      public ITimestampControllerClient TimestampControllerClient;
      public ITransactionPaymentControllerClient TransactionPaymentControllerClient;
      public ITreasuryControllerClient TreasuryControllerClient;
      public IVestingControllerClient VestingControllerClient;
      public Client(HttpClient httpClient, BaseSubscriptionClient subscriptionClient)
      {
         _httpClient = httpClient;
         _subscriptionClient = subscriptionClient;
         AssetsControllerClient = new AssetsControllerClient(_httpClient, _subscriptionClient);
         AuraControllerClient = new AuraControllerClient(_httpClient, _subscriptionClient);
         BalancesControllerClient = new BalancesControllerClient(_httpClient, _subscriptionClient);
         CouncilControllerClient = new CouncilControllerClient(_httpClient, _subscriptionClient);
         CouncilMembershipControllerClient = new CouncilMembershipControllerClient(_httpClient, _subscriptionClient);
         DemocracyControllerClient = new DemocracyControllerClient(_httpClient, _subscriptionClient);
         GameRegistryControllerClient = new GameRegistryControllerClient(_httpClient, _subscriptionClient);
         GrandpaControllerClient = new GrandpaControllerClient(_httpClient, _subscriptionClient);
         MatchmakerControllerClient = new MatchmakerControllerClient(_httpClient, _subscriptionClient);
         ObserversControllerClient = new ObserversControllerClient(_httpClient, _subscriptionClient);
         RunnerControllerClient = new RunnerControllerClient(_httpClient, _subscriptionClient);
         SchedulerControllerClient = new SchedulerControllerClient(_httpClient, _subscriptionClient);
         SidechainControllerClient = new SidechainControllerClient(_httpClient, _subscriptionClient);
         SudoControllerClient = new SudoControllerClient(_httpClient, _subscriptionClient);
         SystemControllerClient = new SystemControllerClient(_httpClient, _subscriptionClient);
         TeerexControllerClient = new TeerexControllerClient(_httpClient, _subscriptionClient);
         TimestampControllerClient = new TimestampControllerClient(_httpClient, _subscriptionClient);
         TransactionPaymentControllerClient = new TransactionPaymentControllerClient(_httpClient, _subscriptionClient);
         TreasuryControllerClient = new TreasuryControllerClient(_httpClient, _subscriptionClient);
         VestingControllerClient = new VestingControllerClient(_httpClient, _subscriptionClient);
      }
   }
}
