//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjunaExample.SubscriptionDemo.RestClient.Mockup
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using AjunaExample.SubscriptionDemo.RestClient.Mockup.Generated.Interfaces;
   using AjunaExample.SubscriptionDemo.RestClient.Mockup.Generated.Clients;
   
   public sealed class MockupClient
   {
      private HttpClient _httpClient;
      public IAssetsControllerMockupClient AssetsControllerClient;
      public IAuraControllerMockupClient AuraControllerClient;
      public IBalancesControllerMockupClient BalancesControllerClient;
      public ICouncilControllerMockupClient CouncilControllerClient;
      public ICouncilMembershipControllerMockupClient CouncilMembershipControllerClient;
      public IDemocracyControllerMockupClient DemocracyControllerClient;
      public IGameRegistryControllerMockupClient GameRegistryControllerClient;
      public IGrandpaControllerMockupClient GrandpaControllerClient;
      public IMatchmakerControllerMockupClient MatchmakerControllerClient;
      public IObserversControllerMockupClient ObserversControllerClient;
      public IRunnerControllerMockupClient RunnerControllerClient;
      public ISchedulerControllerMockupClient SchedulerControllerClient;
      public ISidechainControllerMockupClient SidechainControllerClient;
      public ISudoControllerMockupClient SudoControllerClient;
      public ISystemControllerMockupClient SystemControllerClient;
      public ITeerexControllerMockupClient TeerexControllerClient;
      public ITimestampControllerMockupClient TimestampControllerClient;
      public ITransactionPaymentControllerMockupClient TransactionPaymentControllerClient;
      public ITreasuryControllerMockupClient TreasuryControllerClient;
      public IVestingControllerMockupClient VestingControllerClient;
      public MockupClient(HttpClient httpClient)
      {
         _httpClient = httpClient;
         AssetsControllerClient = new AssetsControllerMockupClient(_httpClient);
         AuraControllerClient = new AuraControllerMockupClient(_httpClient);
         BalancesControllerClient = new BalancesControllerMockupClient(_httpClient);
         CouncilControllerClient = new CouncilControllerMockupClient(_httpClient);
         CouncilMembershipControllerClient = new CouncilMembershipControllerMockupClient(_httpClient);
         DemocracyControllerClient = new DemocracyControllerMockupClient(_httpClient);
         GameRegistryControllerClient = new GameRegistryControllerMockupClient(_httpClient);
         GrandpaControllerClient = new GrandpaControllerMockupClient(_httpClient);
         MatchmakerControllerClient = new MatchmakerControllerMockupClient(_httpClient);
         ObserversControllerClient = new ObserversControllerMockupClient(_httpClient);
         RunnerControllerClient = new RunnerControllerMockupClient(_httpClient);
         SchedulerControllerClient = new SchedulerControllerMockupClient(_httpClient);
         SidechainControllerClient = new SidechainControllerMockupClient(_httpClient);
         SudoControllerClient = new SudoControllerMockupClient(_httpClient);
         SystemControllerClient = new SystemControllerMockupClient(_httpClient);
         TeerexControllerClient = new TeerexControllerMockupClient(_httpClient);
         TimestampControllerClient = new TimestampControllerMockupClient(_httpClient);
         TransactionPaymentControllerClient = new TransactionPaymentControllerMockupClient(_httpClient);
         TreasuryControllerClient = new TreasuryControllerMockupClient(_httpClient);
         VestingControllerClient = new VestingControllerMockupClient(_httpClient);
      }
   }
}
